version: "3.9"

services:
  central:
    build: ./server
    volumes:
      - ./shared:/app/shared
    ports:
      - "5000:5000"

  client1:
    build: ./client
    depends_on:
      - central

  client2:
    build: ./client
    depends_on:
      - central

  client3:
    build: ./client
    depends_on:
      - central
